[package]
name = "csv2md"
version = "0.1.0"
edition = "2018"
authors = [ "Kurt Schwind <Kurt.Schwind@gmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
clippy = "0.0.302"
csv = "~1"
